"""init

Revision ID: d8a41b1158d2
Revises: 
Create Date: 2026-02-15 16:01:21.582362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8a41b1158d2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chunking_jobs',
    sa.Column('file_id', sa.BigInteger(), nullable=False),
    sa.Column('kb_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'processing', 'processed', 'failed', 'canceled', name='chunking_status_enum'), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column("vectorized_at", sa.DateTime(timezone=True), nullable=True),

    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kb_id', 'file_id', name='uq_job_identity')
    )
    op.create_index(op.f('ix_chunking_jobs_file_id'), 'chunking_jobs', ['file_id'], unique=False)
    op.create_index(op.f('ix_chunking_jobs_kb_id'), 'chunking_jobs', ['kb_id'], unique=False)
    op.create_table('chunks',
    sa.Column('file_id', sa.BigInteger(), nullable=False),
    sa.Column('kb_id', sa.UUID(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column("vectorized_at", sa.DateTime(timezone=True), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('chunking_version', sa.String(length=50), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kb_id', 'file_id', 'page', 'chunk_index', 'chunking_version', name='uq_chunk_identity')
    )
    op.create_index('ix_chunks_file_chunk', 'chunks', ['file_id', 'chunk_index'], unique=False)
    op.create_index(op.f('ix_chunks_file_id'), 'chunks', ['file_id'], unique=False)
    op.create_index(op.f('ix_chunks_kb_id'), 'chunks', ['kb_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chunks_kb_id'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_file_id'), table_name='chunks')
    op.drop_index('ix_chunks_file_chunk', table_name='chunks')
    op.drop_table('chunks')
    op.drop_index(op.f('ix_chunking_jobs_kb_id'), table_name='chunking_jobs')
    op.drop_index(op.f('ix_chunking_jobs_file_id'), table_name='chunking_jobs')
    op.drop_table('chunking_jobs')
    # ### end Alembic commands ###
